`default_nettype none

module draft_verify_state_controller_top (
    input  logic clk,
    input  logic rst,
    input  logic abort_request,
    output logic abort_ack,
    input  logic start_valid,
    output logic start_ready,
    input  logic [5:0] start_row_count,
    input  logic [31:0] start_masked_mask,
    input  logic [31:0] start_tentative_mask,
    input  logic [31:0] start_locked_mask,
    input  logic [31:0] start_mask_token_id,
    input  logic [16:0] start_vocabulary_size,
    input  logic [15:0] start_high_confidence_threshold_bf16,
    input  logic [15:0] start_tail_high_confidence_threshold_bf16,
    input  logic [15:0] start_low_confidence_threshold_bf16,
    input  logic [15:0] start_verify_threshold_bf16,
    input  logic [15:0] start_stability_bonus_bf16,
    input  logic [15:0] start_budget_scale_bf16,
    input  logic [15:0] start_scheduled_quota,
    input logic [5:0] start_max_handoff_tokens,
    input  logic [15:0] start_remaining_forwards,
    input  logic [15:0] start_step_index,
    input  logic [15:0] start_tail_after_step,
    input  logic [15:0] start_maturity_age,
    input  logic start_tail_threshold_enable,
    input  logic start_tail_all,
    input  logic start_tail_bypass_all,
    input  logic start_tail_bypass_stable_only,
    input  logic [1:0] start_closeout_kind,
    input  logic start_canonical_future,
    input logic start_source_a_handoff,
    input  logic start_transfer_only,
    input  logic [31:0] start_observed_mask,
    input  logic row_valid,
    output logic row_ready,
    input  logic [4:0] row_index,
    input  logic [31:0] row_token_id,
    input  logic [31:0] row_last_top1,
    input  logic signed [15:0] row_precision_age,
    input  logic [10:0] row_token_position,
    input  logic [1:0] row_origin,
    input  logic [3:0] activation_bits,
    input  logic row_cache_valid,
    input  logic row_refresh_required,
    input  logic row_prediction_flag,
    input  logic [31:0] row_candidate_top1,
    input  logic [15:0] row_selected_probability_bf16,
    input  logic [15:0] row_action_confidence_bf16,
    input logic row_action_confidence_valid,
    input logic row_source_a, row_source_a_pending,
    output logic next_token_source_a_pending,
    output logic [15:0] next_token_action_confidence_bf16,
    output logic next_token_action_confidence_valid,
    input  logic row_suppressed_winner,
    output logic bf16_abort_request,
    input  logic bf16_abort_ack,
    output logic bf16_req_valid,
    input  logic bf16_req_ready,
    output hardware_types_pkg::bf16_request_t bf16_req,
    input  logic bf16_rsp_valid,
    output logic bf16_rsp_ready,
    input  hardware_types_pkg::bf16_response_t bf16_rsp,
    output logic next_token_valid,
    input  logic next_token_ready,
    output logic [4:0] next_token_index,
    output logic [31:0] next_token_token_id,
    output logic [31:0] next_token_last_top1,
    output logic signed [15:0] next_token_precision_age,
    output logic [10:0] next_token_token_position,
    output logic [1:0] next_token_state,
    output logic [1:0] next_token_origin,
    output logic [3:0] next_activation_bits,
    output logic next_token_cache_valid,
    output logic next_token_refresh_required,
    output logic next_token_prediction_flag,
    output logic done_valid,
    input  logic done_ready,
    output logic error,
    output logic [7:0] error_id,
    output logic [31:0] confirmed_mask,
    output logic [31:0] remasked_mask,
    output logic [31:0] selected_mask,
    output logic [31:0] direct_locked_mask,
    output logic [31:0] stable_tentative_mask,
    output logic [31:0] fallback_tentative_mask,
    output logic [31:0] mandatory_refresh_mask,
    output logic [31:0] cache_commit_mask,
    output logic [31:0] cache_invalidate_mask,
    output logic [31:0] cache_keep_mask,
    output logic [31:0] token_changed_mask,
    output logic [31:0] tail_closed_mask
);
    draft_verify_state_controller controller (
        .next_token_change_flags(), .next_token_change_confidence_bf16(),
        .clk, .rst, .abort_request, .abort_ack,
        .start_valid, .start_ready, .start_row_count,
        .start_masked_mask, .start_tentative_mask, .start_locked_mask,
        .start_mask_token_id, .start_vocabulary_size,
        .start_high_confidence_threshold_bf16, .start_tail_high_confidence_threshold_bf16,
        .start_low_confidence_threshold_bf16, .start_verify_threshold_bf16,
        .start_stability_bonus_bf16, .start_budget_scale_bf16,
        .start_scheduled_quota, .start_max_handoff_tokens, .start_remaining_forwards,
        .start_step_index, .start_tail_after_step, .start_maturity_age,
        .start_tail_threshold_enable, .start_tail_all,
        .start_tail_bypass_all,
        .start_tail_bypass_stable_only,
        .start_closeout_kind,
        .start_canonical_future, .start_source_a_handoff, .row_source_a, .row_source_a_pending,
        .next_token_source_a_pending, .start_transfer_only, .start_observed_mask,
        .row_valid, .row_ready, .row_index, .row_token_id,
        .row_last_top1, .row_precision_age, .row_token_position,
        .row_origin, .activation_bits, .row_cache_valid, .row_refresh_required,
        .row_prediction_flag, .row_candidate_top1,
        .row_selected_probability_bf16, .row_action_confidence_bf16,
        .row_action_confidence_valid, .next_token_action_confidence_bf16, .next_token_action_confidence_valid,
        .row_suppressed_winner,
        .bf16_abort_request, .bf16_abort_ack, .bf16_req_valid,
        .bf16_req_ready, .bf16_req, .bf16_rsp_valid, .bf16_rsp_ready,
        .bf16_rsp, .next_token_valid, .next_token_ready, .next_token_index,
        .next_token_token_id, .next_token_last_top1,
        .next_token_precision_age, .next_token_token_position,
        .next_token_state, .next_token_origin, .next_activation_bits,
        .next_token_cache_valid, .next_token_refresh_required,
        .next_token_prediction_flag,
        .done_valid, .done_ready, .error, .error_id,
        .confirmed_mask, .remasked_mask, .selected_mask,
        .direct_locked_mask, .stable_tentative_mask,
        .fallback_tentative_mask, .mandatory_refresh_mask,
        .cache_commit_mask, .cache_invalidate_mask, .cache_keep_mask,
        .token_changed_mask, .tail_closed_mask);
endmodule

`default_nettype wire
