`default_nettype none

module softmax_engine_start_top (
    input  logic clk,
    input  logic rst,
    input  logic abort_request,
    output logic abort_ack,
    input  logic start_valid,
    output logic start_ready,
    input  logic [5:0] start_row_count,
    input  logic [5:0] start_head_count,
    input  logic [11:0] start_row_length,
    output logic busy,
    output logic done,
    output logic error,
    output logic [3:0] error_id,
    output logic tile_read_req_valid,
    input  logic tile_read_req_ready,
    output logic [1:0] tile_read_pass,
    output logic [23:0] tile_read_group_base,
    output logic [5:0] tile_read_head,
    output logic [5:0] tile_read_row_base,
    output logic [11:0] tile_read_key,
    output logic [15:0] tile_read_tag,
    output logic bf16_write_valid,
    output logic quantized_write_valid,
    output logic scale_write_valid,
    output logic [63:0] completed_command_count
);
    softmax_engine engine (
        .start_capture_probability_enable(1'b0), .capture_probability_ready(1'b1),
        .capture_probability_valid(), .capture_probability_head(),
        .capture_probability_row_base(), .capture_probability_row_mask(),
        .clk(clk),
        .rst(rst),
        .abort_request(abort_request),
        .abort_ack(abort_ack),
        .start_valid(start_valid),
        .start_ready(start_ready),
        .start_row_count(start_row_count),
        .start_head_count(start_head_count),
        .start_row_length(start_row_length),
        .start_score_base(24'h010000),
        .start_score_head_stride(24'h003000),
        .start_score_row_stride(24'h000100),
        .start_probability_base(24'h090000),
        .start_probability_head_stride(24'h003000),
        .start_probability_row_stride(24'h000100),
        .busy(busy),
        .done_pulse(done),
        .error(error),
        .error_id(error_id),
        .tile_read_req_valid(tile_read_req_valid),
        .tile_read_req_ready(tile_read_req_ready),
        .tile_read_pass(tile_read_pass),
        .tile_read_group_base(tile_read_group_base),
        .tile_read_head(tile_read_head),
        .tile_read_row_base(tile_read_row_base),
        .tile_read_key(tile_read_key),
        .tile_read_tag(tile_read_tag),
        .tile_read_rsp_valid(1'b0),
        .tile_read_rsp_ready(),
        .tile_read_rsp_values('0),
        .tile_read_rsp_lane_mask('0),
        .tile_read_rsp_tag('0),
        .bf16_write_valid(bf16_write_valid),
        .bf16_write_ready(1'b0),
        .bf16_write_probability(),
        .bf16_write_group_base(),
        .bf16_write_head(),
        .bf16_write_row_base(),
        .bf16_write_key(),
        .bf16_write_values(),
        .bf16_write_lane_mask(),
        .bf16_write_tag(),
        .quantized_write_valid(quantized_write_valid),
        .quantized_write_ready(1'b0),
        .quantized_write_head(),
        .quantized_write_row_base(),
        .quantized_write_key(),
        .quantized_write_values(),
        .quantized_write_lane_mask(),
        .quantized_write_tag(),
        .scale_write_valid(scale_write_valid),
        .scale_write_ready(1'b0),
        .scale_write_head(),
        .scale_write_row_base(),
        .scale_write_values(),
        .scale_write_row_mask(),
        .scratch_read_valid(),
        .scratch_read_ready(1'b0),
        .scratch_read_bank(),
        .scratch_read_left_address(),
        .scratch_read_right_address(),
        .scratch_read_tag(),
        .scratch_rsp_valid(1'b0),
        .scratch_rsp_ready(),
        .scratch_rsp_left_data('0),
        .scratch_rsp_right_data('0),
        .scratch_rsp_tag('0),
        .scratch_write_valid(),
        .scratch_write_ready(1'b0),
        .scratch_write_bank(),
        .scratch_write_address(),
        .scratch_write_data(),
        .scratch_write_byte_enable(),
        .vector_req_valid(),
        .vector_req_ready(1'b0),
        .vector_req_operation(),
        .vector_req_values(),
        .vector_req_paired_values(),
        .vector_req_factor0_values(),
        .vector_req_factor1_values(),
        .vector_req_lane_mask(),
        .vector_req_tag(),
        .vector_rsp_valid(1'b0),
        .vector_rsp_ready(),
        .vector_rsp_values('0),
        .vector_rsp_lane_mask('0),
        .vector_rsp_tag('0),
        .max_req_valid(),
        .max_req_ready(1'b0),
        .max_req_magnitude(),
        .max_req_values(),
        .max_req_lane_mask(),
        .max_req_tag(),
        .max_rsp_valid(1'b0),
        .max_rsp_ready(),
        .max_rsp_values('0),
        .max_rsp_row_mask('0),
        .max_rsp_tag('0),
        .reduction_req_valid(),
        .reduction_req_ready(1'b0),
        .reduction_req_values(),
        .reduction_req_lane_mask(),
        .reduction_req_tag(),
        .reduction_rsp_valid(1'b0),
        .reduction_rsp_ready(),
        .reduction_rsp_values('0),
        .reduction_rsp_row_mask('0),
        .reduction_rsp_tag('0),
        .exp_req_valid(), .exp_req_ready(1'b0),
        .exp_req_delta_values(), .exp_req_lane_mask(), .exp_req_tag(),
        .exp_rsp_valid(1'b0), .exp_rsp_ready(), .exp_rsp_values('0),
        .exp_rsp_lane_mask('0), .exp_rsp_tag('0),
        .reciprocal_req_valid(), .reciprocal_req_ready(1'b0),
        .reciprocal_req_sum_values(), .reciprocal_req_row_mask(),
        .reciprocal_req_tag(), .reciprocal_rsp_valid(1'b0),
        .reciprocal_rsp_ready(), .reciprocal_rsp_values('0),
        .reciprocal_rsp_row_mask('0), .reciprocal_rsp_tag('0),
        .quant_scale_req_valid(),
        .quant_scale_req_ready(1'b0),
        .quant_scale_req_row_max_abs(),
        .quant_scale_req_row_mask(),
        .quant_scale_rsp_valid(1'b0),
        .quant_scale_rsp_ready(),
        .quant_scale_rsp_values('0),
        .quant_values_req_valid(),
        .quant_values_req_ready(1'b0),
        .quant_values_req_values(),
        .quant_values_req_lane_mask(),
        .quant_values_req_tag(),
        .quant_values_rsp_valid(1'b0),
        .quant_values_rsp_ready(),
        .quant_values_rsp_values('0),
        .quant_values_rsp_lane_mask('0),
        .quant_values_rsp_tag('0),
        .accepted_source_tile_count(),
        .accepted_bf16_write_count(),
        .accepted_quantized_write_count(),
        .accepted_scratch_read_count(),
        .accepted_scratch_write_count(),
        .accepted_vector_request_count(),
        .accepted_max_request_count(),
        .accepted_reduction_request_count(),
        .accepted_quantized_value_count(),
        .completed_command_count(completed_command_count)
    );
endmodule

`default_nettype wire
