`default_nettype none

module token_issue_embedding_top (
    input  logic clk,
    input  logic rst,

    input  logic pack_start_valid,
    output logic pack_start_ready,
    input  logic [5:0] pack_start_rows,
    input  logic [15:0] pack_start_round,
    input  logic [15:0] pack_start_first_row,
    input  logic pack_row_valid,
    output logic pack_row_ready,
    input  logic [5:0] pack_row_index,
    input  logic [16:0] pack_row_source_index,
    input  logic [10:0] pack_row_token_position,
    input  logic [10:0] pack_row_kv_index,
    input  logic [3:0] pack_activation_bits,
    input  logic [7:0] pack_row_query_group,
    input  logic [7:0] pack_row_cache_group,
    output logic pack_beat_valid,
    input  logic pack_beat_ready,
    output logic [127:0] pack_beat_data,
    output logic pack_beat_last,
    output logic pack_done_valid,
    input  logic pack_done_ready,
    output logic pack_error,

    input  logic metadata_start_valid,
    output logic metadata_start_ready,
    input  logic [2559:0] configuration_bits,
    output logic metadata_request_valid,
    input  logic metadata_request_ready,
    output logic [63:0] metadata_request_address,
    output logic [31:0] metadata_request_bytes,
    input  logic metadata_response_valid,
    output logic metadata_response_ready,
    input  logic [127:0] metadata_response_data,
    input  logic [15:0] metadata_response_byte_enable,
    input  logic metadata_response_last,
    input  logic metadata_request_done,
    input  logic metadata_request_error,
    output logic loaded_token_valid,
    output logic [10:0] loaded_token_position,
    output logic loaded_token_kv_write,
    output logic metadata_done_valid,
    input  logic metadata_done_ready,
    output logic metadata_done_error,
    output logic metadata_config_valid,
    input  logic metadata_config_release,
    output logic [5:0] metadata_round,
    output logic metadata_last_round,
    output logic [5:0] metadata_active_rows,

    input  logic hidden_start_valid,
    output logic hidden_start_ready,
    input  logic [63:0] resident_base,
    input  logic [63:0] resident_limit,
    input  logic [63:0] embedding_base,
    input  logic [63:0] embedding_limit,
    output logic hidden_request_valid,
    input  logic hidden_request_ready,
    output logic [63:0] hidden_request_address,
    output logic [31:0] hidden_request_bytes,
    input  logic hidden_request_done,
    input  logic hidden_request_error,
    input  logic hidden_data_valid,
    output logic hidden_data_ready,
    input  logic [127:0] hidden_data,
    input  logic [15:0] hidden_byte_enable,
    input  logic hidden_data_last,
    output logic hidden_local_write_valid,
    input  logic hidden_local_write_ready,
    output logic [5:0] hidden_local_write_row,
    output logic [8:0] hidden_local_write_word,
    output logic [127:0] hidden_local_write_data,
    output logic hidden_done_valid,
    input  logic hidden_done_ready,
    output logic hidden_error,
    output logic [63:0] hidden_request_count,
    output logic [63:0] hidden_data_count,
    output logic [63:0] hidden_local_write_count
);
    logic [287:0] physical_to_local;
    logic [815:0] row_source_index;
    logic [47:0] row_embedding_source;
    logic hidden_abort_ack;
    logic hidden_busy;
    logic hidden_done_for_ffn;
    logic [3:0] hidden_error_id;

    token_issue_packer packer (
        .clk, .rst, .abort_request(1'b0), .abort_ack(),
        .start_valid(pack_start_valid), .start_ready(pack_start_ready),
        .start_row_count(pack_start_rows), .start_sequence_length(12'd512),
        .start_token_batch_index(pack_start_round),
        .start_first_token_ordinal(pack_start_first_row),
        .start_metadata_version(32'h10203040),
        .start_capture_index(32'h50607080),
        .row_valid(pack_row_valid), .row_ready(pack_row_ready),
        .row_index(pack_row_index), .row_source_index(pack_row_source_index),
        .row_token_position(pack_row_token_position),
        .row_kv_write_disable(1'b0), .row_kv_index(pack_row_kv_index), .row_embedding_source(1'b1),
        .activation_bits(pack_activation_bits), .row_query_group(pack_row_query_group),
        .row_cache_group(pack_row_cache_group),
        .beat_valid(pack_beat_valid), .beat_ready(pack_beat_ready),
        .beat_data(pack_beat_data), .beat_last(pack_beat_last),
        .done_valid(pack_done_valid), .done_ready(pack_done_ready),
        .error(pack_error), .error_id(), .compute_group_count(),
        .semantic_group_count()
    );

    token_metadata_loader loader (
        .start_l31_layout(1'b0),
        .clk, .rst, .start_valid(metadata_start_valid),
        .start_ready(metadata_start_ready),
        .start_configuration_bits(configuration_bits),
        .dma_request_valid(metadata_request_valid),
        .dma_request_ready(metadata_request_ready),
        .dma_request_address(metadata_request_address),
        .dma_request_bytes(metadata_request_bytes),
        .dma_response_valid(metadata_response_valid),
        .dma_response_ready(metadata_response_ready),
        .dma_response_data(metadata_response_data),
        .dma_response_byte_enable(metadata_response_byte_enable),
        .dma_response_last(metadata_response_last),
        .dma_request_done(metadata_request_done),
        .dma_request_error(metadata_request_error),
        .loaded_token_valid, .loaded_token_position, .loaded_token_kv_write,
        .done_valid(metadata_done_valid), .done_ready(metadata_done_ready),
        .done_error(metadata_done_error), .done_error_id(),
        .config_valid(metadata_config_valid),
        .config_release(metadata_config_release), .total_token_count(),
        .token_batch_index(metadata_round), .last_round(metadata_last_round),
        .active_token_count(metadata_active_rows), .compute_group_count(),
        .output_subset_enable(), .qkvo_group_end(), .output_token_count(),
        .output_compute_group_count(), .row_kv_write_disable(),
        .sequence_length(), .physical_to_local, .local_to_physical(),
        .token_position(), .row_kv_index(), .matmul_row_valid(),
        .row_source_index, .row_embedding_source, .row_precision_bits(),
        .row_query_group(), .row_cache_group(), .row_compute_group(),
        .row_pe_slot(), .row_phase_mask()
    );

    hidden_transfer hidden (
        .clk, .rst, .abort_request(1'b0), .abort_ack(hidden_abort_ack),
        .start_valid(hidden_start_valid), .start_ready(hidden_start_ready),
        .start_operation(2'd0), .start_active_rows(metadata_active_rows),
        .start_physical_to_token_ordinal(physical_to_local),
        .start_direct_row_index_enable(1'b1),
        .start_direct_row_index(528'd0),
        .start_source_descriptor_enable(1'b1),
        .start_source_index(row_source_index),
        .start_source_embedding(row_embedding_source),
        .start_embedding_base(embedding_base),
        .start_embedding_limit(embedding_limit),
        .start_ddr_base(resident_base), .start_ddr_limit(resident_limit),
        .start_for_ffn(1'b0), .busy(hidden_busy),
        .done_valid(hidden_done_valid), .done_ready(hidden_done_ready),
        .done_for_ffn(hidden_done_for_ffn), .error(hidden_error),
        .error_id(hidden_error_id),
        .read_request_valid(hidden_request_valid),
        .read_request_ready(hidden_request_ready),
        .read_request_address(hidden_request_address),
        .read_request_bytes(hidden_request_bytes), .read_request_tag(),
        .read_request_done(hidden_request_done),
        .read_request_error(hidden_request_error),
        .read_data_valid(hidden_data_valid), .read_data_ready(hidden_data_ready),
        .read_data(hidden_data), .read_byte_enable(hidden_byte_enable),
        .read_data_last(hidden_data_last), .read_data_tag(8'h8f),
        .write_request_valid(), .write_request_ready(1'b0),
        .write_request_address(), .write_request_bytes(), .write_request_tag(),
        .write_request_done(1'b0), .write_request_error(1'b0),
        .write_data_valid(), .write_data_ready(1'b0), .write_data(),
        .write_byte_enable(), .write_data_last(),
        .local_write_valid(hidden_local_write_valid),
        .local_write_ready(hidden_local_write_ready),
        .local_write_physical_row(hidden_local_write_row),
        .local_write_channel_word(hidden_local_write_word),
        .local_write_data(hidden_local_write_data),
        .local_write_byte_enable(), .local_read_valid(),
        .local_read_ready(1'b0), .local_read_physical_row(),
        .local_read_channel_word(), .local_read_response_valid(1'b0),
        .local_read_data(128'd0),
        .accepted_dma_request_count(hidden_request_count),
        .accepted_dma_data_count(hidden_data_count),
        .accepted_local_request_count(hidden_local_write_count)
    );
endmodule

`default_nettype wire
