`default_nettype none

package forward_postprocess_config_pkg;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_BYTES = 192;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_ALIGNMENT = 16;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_MAGIC_OFFSET = 0;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_VERSION_OFFSET = 4;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_HEADER_BYTES_OFFSET = 6;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_TOTAL_BYTES_OFFSET = 8;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_FLAGS_OFFSET = 12;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_FORWARD_EVENT_ENTRY_BYTES_OFFSET = 14;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_VOCABULARY_SIZE_OFFSET = 16;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_INPUT_FEATURES_OFFSET = 20;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_CANDIDATE_LANES_OFFSET = 22;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_RAW_W8_LAYOUT_ID_OFFSET = 24;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_STATE_FORMAT_OFFSET = 28;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_DESCRIPTOR_FORMAT_OFFSET = 30;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_RAW_W8_BASE_OFFSET = 32;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_RAW_W8_LIMIT_OFFSET = 40;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_WEIGHT_SCALE_BASE_OFFSET = 48;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_WEIGHT_SCALE_LIMIT_OFFSET = 56;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_CURRENT_STATE_BASE_OFFSET = 64;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_CURRENT_STATE_LIMIT_OFFSET = 72;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_NEXT_STATE_BASE_OFFSET = 80;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_NEXT_STATE_LIMIT_OFFSET = 88;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_SUPPRESSED_TOKEN_BASE_OFFSET = 96;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_SUPPRESSED_TOKEN_LIMIT_OFFSET = 104;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_FORWARD_EVENT_BASE_OFFSET = 112;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_FORWARD_EVENT_LIMIT_OFFSET = 120;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_COMPLETION_BASE_OFFSET = 128;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_COMPLETION_LIMIT_OFFSET = 136;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_MASK_TOKEN_ID_OFFSET = 144;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_COMPLETION_VERSION_OFFSET = 148;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_HIGH_CONFIDENCE_THRESHOLD_BF16_OFFSET = 152;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_TAIL_HIGH_CONFIDENCE_THRESHOLD_BF16_OFFSET = 154;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_LOW_CONFIDENCE_THRESHOLD_BF16_OFFSET = 156;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_VERIFY_THRESHOLD_BF16_OFFSET = 158;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_STABILITY_BONUS_BF16_OFFSET = 160;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_BUDGET_SCALE_BF16_OFFSET = 162;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_SCALE_PREFETCH_PANEL_COUNT_OFFSET = 164;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_BLOCK_CONFIGURATION_ENTRY_BYTES_OFFSET = 166;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_FINAL_RMS_EPSILON_BF16_OFFSET = 168;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_STATE_ENTRY_BYTES_OFFSET = 170;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_SUPPRESSED_TOKEN_ENTRY_BYTES_OFFSET = 172;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_COMPLETION_ENTRY_BYTES_OFFSET = 174;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_BLOCK_CONFIGURATION_BASE_OFFSET = 176;
    localparam int unsigned FORWARD_POSTPROCESS_CONFIG_BLOCK_CONFIGURATION_LIMIT_OFFSET = 184;
endpackage

`default_nettype wire
